services:
  - type: web
    name: nereus-backend
    runtime: python
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DEMO_MODE
        value: true
      - key: PYTHON_VERSION
        value: 3.11.0
